/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Token } from "./ERC20Token";
export type { IERC20 } from "./IERC20";

export { ERC20Token__factory } from "./factories/ERC20Token__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
